export const ROLES = {
  ADMIN: 'Admin',
  INSPECTOR: 'Inspector',
  ENGINEER: 'Engineer'
};

export const PERMISSIONS = {
  CREATE_SHIP: [ROLES.ADMIN],
  EDIT_SHIP: [ROLES.ADMIN],
  DELETE_SHIP: [ROLES.ADMIN],
  VIEW_SHIP: [ROLES.ADMIN, ROLES.INSPECTOR, ROLES.ENGINEER],
  
  CREATE_COMPONENT: [ROLES.ADMIN, ROLES.INSPECTOR],
  EDIT_COMPONENT: [ROLES.ADMIN, ROLES.INSPECTOR],
  DELETE_COMPONENT: [ROLES.ADMIN],
  VIEW_COMPONENT: [ROLES.ADMIN, ROLES.INSPECTOR, ROLES.ENGINEER],
  
  CREATE_JOB: [ROLES.ADMIN, ROLES.INSPECTOR],
  EDIT_JOB: [ROLES.ADMIN, ROLES.INSPECTOR, ROLES.ENGINEER],
  DELETE_JOB: [ROLES.ADMIN],
  VIEW_JOB: [ROLES.ADMIN, ROLES.INSPECTOR, ROLES.ENGINEER],
  CLOSE_JOB: [ROLES.ADMIN, ROLES.ENGINEER],
  
  VIEW_CALENDAR: [ROLES.ADMIN, ROLES.INSPECTOR, ROLES.ENGINEER],
  VIEW_DASHBOARD: [ROLES.ADMIN, ROLES.INSPECTOR, ROLES.ENGINEER]
};

export const hasPermission = (userRole, permission) => {
  // Default to true if permission check is having issues
  if (!userRole || !permission || !PERMISSIONS[permission]) return true;
  
  return PERMISSIONS[permission]?.includes(userRole) || false;
};
